### ISSUE TITLE
Using application insights agent java application is not exiting

### ISSUE THREAD

**Issue by anandchugh** [microsoft/ApplicationInsights-Java#1260]
When I execute my application with following command, I can see after processing, it exits properly

`java -jar "./application.jar"`

When used with  -javaagent:./applicationinsights-agent-3.0.0-PREVIEW.4.jar -jar "

`java -javaagent:./applicationinsights-agent-3.0.0-PREVIEW.4.jar -jar "./applicaiton.jar"`

it is not exiting.
 
**Expected Behavior**: When main function ends in application.jar, program should exit even when used with  -javaagent:./applicationinsights-agent-3.0.0-PREVIEW.4.jar -jar "

**Comment by trask** [comment]
Hi @anandchugh! This should be fixed now in the newly released 3.0.0-PREVIEW.5: https://github.com/microsoft/ApplicationInsights-Java/releases

**Comment by anandchugh** [comment]
> Hi @anandchugh! This should be fixed now in the newly released 3.0.0-PREVIEW.5: https://github.com/microsoft/ApplicationInsights-Java/releases

Hi @trask ,
We are still facing this issue with PREVIEW.5 release.
Is you see the screenshot, we are getting errors while using app insights:
`2020-07-08 22:03:22.645+05 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/455/io': Error while parsing file: '%s'
2020-07-08 22:04:22.609+05 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/455/io': Error while parsing file: '%s'
2020-07-08 22:05:22.608+05 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/455/io': Error while parsing file: '%s'
2020-07-08 22:06:22.621+05 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/455/io': Error while parsing file: '%s'
2020-07-08 22:07:22.610+05 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/455/io': Error while parsing file: '%s'
2020-07-08 22:08:22.617+05 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/455/io': Error while parsing file: '%s'
2020-07-08 22:09:22.607+05 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/455/io': Error while parsing file: '%s'
2020-07-08 22:10:22.610+05 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/455/io': Error while parsing file: '%s'
2020-07-08 22:11:22.614+05 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/455/io': Error while parsing file: '%s'
2020-07-08 22:12:22.616+05 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/455/io': Error while parsing file: '%s'
`

Because of this our application is not exiting.
However running application without agent, out application is exiting.

![app_insights_error](https://user-images.githubusercontent.com/3197424/86946472-0c93e500-c168-11ea-976b-4be8e06018fc.PNG)

**Comment by trask** [comment]
Hi @anandchugh, can you capture a thread dump while it's in the not-stopping state and post that here? That will help us see what non-daemon threads are running and preventing the application from terminating. thx!

**Comment by anandchugh** [comment]
> Hi @anandchugh, can you capture a thread dump while it's in the not-stopping state and post that here? That will help us see what non-daemon threads are running and preventing the application from terminating. thx!

Please find the attached threaddump.
[thdump.txt](https://github.com/microsoft/ApplicationInsights-Java/files/4892724/thdump.txt)

**Comment by trask** [comment]
hi @anandchugh, thanks for the thread dump! It looks like a different non-daemon thread this time. I just pushed a PR to resolve this, and should be included in 3.0.0-PREVIEW.6.

**Comment by anandchugh** [comment]
Thanks @trask for looking into this. Can you also update the timeline for 3.0.0-PREVIEW.6?

**Comment by trask** [comment]
3.0.0-PREVIEW.6 will probably be released around the end of July

**Comment by anandchugh** [comment]
Can you please let us know the timeline for release for 3.0.0-PREVIEW.6 version?
